name: staurolite
description: a simple backend for static site generators using dart 
version: 1.1.1
# homepage: https://www.example.com

environment:
  sdk: '>=2.18.1 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
dependencies:
  args: ^2.3.1
  path: ^1.8.0
  serve: ^3.0.1
  markdown: ^6.0.1
  highlight: ^0.7.0
  html: ^0.15.1
